// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250807115322_paymentandvotes")]
    partial class paymentandvotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e892977d-9575-4c42-9f6f-d72534568ae7"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6087),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6089),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year"
                        },
                        new
                        {
                            Id = new Guid("86c34bdd-1b48-4128-8a23-2b6bc4c6044a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6162),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6163),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year"
                        },
                        new
                        {
                            Id = new Guid("d7f2d0aa-4ee6-4b66-ada8-c434279a91fd"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6165),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6165),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year"
                        },
                        new
                        {
                            Id = new Guid("463a4643-033b-4430-baba-088feea18fe3"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6167),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6167),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year"
                        },
                        new
                        {
                            Id = new Guid("86de2dbc-d9d5-4db8-8e96-1cacf6db18c2"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6169),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6169),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food"
                        },
                        new
                        {
                            Id = new Guid("4130c9ea-b535-4a72-bd59-10e05eaac9e6"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6171),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6171),
                            IsDeleted = false,
                            Name = "Most Creative Baker"
                        },
                        new
                        {
                            Id = new Guid("d2b2c896-0aa3-4364-9db5-68afe5e5b7ec"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6173),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6173),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year"
                        },
                        new
                        {
                            Id = new Guid("8a8e1816-1a7a-4a9a-b05c-277653ef4345"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6175),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6175),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand"
                        },
                        new
                        {
                            Id = new Guid("b1a1e6b3-2a1f-406d-855e-009023eb329f"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6177),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6177),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year"
                        },
                        new
                        {
                            Id = new Guid("64e5d723-9f71-4063-a4e8-099b9b992410"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6181),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6181),
                            IsDeleted = false,
                            Name = "Craft Mastery Award"
                        },
                        new
                        {
                            Id = new Guid("478b3358-5565-45af-88ae-7ca62f608fd8"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6182),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6183),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year"
                        },
                        new
                        {
                            Id = new Guid("b700bfc7-2c07-4b5f-b639-0e8ac82e483a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6184),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6184),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year"
                        },
                        new
                        {
                            Id = new Guid("b6002b1d-dd17-473e-a7fe-3199f700be5e"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6186),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6186),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand"
                        },
                        new
                        {
                            Id = new Guid("d9d26d19-7927-4bf0-8001-84049f06c900"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6187),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6188),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business"
                        },
                        new
                        {
                            Id = new Guid("e885efa5-6022-49a8-84c4-ea9d1eea2f86"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6189),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6189),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year"
                        },
                        new
                        {
                            Id = new Guid("5a4e2bb6-e672-4075-94a0-031220a3c499"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6191),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6191),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail"
                        },
                        new
                        {
                            Id = new Guid("b6105429-5ce9-4415-8298-83dec1dce4d8"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6193),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6193),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year"
                        },
                        new
                        {
                            Id = new Guid("4fe046c9-bcc1-4a19-a1a0-a50a55369bfb"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6197),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6197),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year"
                        },
                        new
                        {
                            Id = new Guid("3f18f9c9-f9ea-4bce-83b5-d0873bf53dda"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6199),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6199),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year"
                        },
                        new
                        {
                            Id = new Guid("dc7b36ac-5cf8-4c4d-bf98-9c515a7e63ff"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6200),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6201),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year"
                        },
                        new
                        {
                            Id = new Guid("aeb7dc78-8082-4dd1-91a0-b204b2a3b78f"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6202),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6202),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year"
                        },
                        new
                        {
                            Id = new Guid("8dc601dc-8852-4ac6-859f-671efd63ce54"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6204),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6204),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA"
                        },
                        new
                        {
                            Id = new Guid("007310b9-2bb9-48fe-9e3a-883d20b0f6b6"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6206),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6206),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year"
                        },
                        new
                        {
                            Id = new Guid("4631ab50-7a2e-4e3d-9a84-0542bc957c73"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6207),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6208),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence"
                        },
                        new
                        {
                            Id = new Guid("adb652e7-d1c4-4119-ad2e-e9006c5c152e"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6209),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6209),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year"
                        },
                        new
                        {
                            Id = new Guid("e9867b49-07d8-475a-98ad-fa8380669695"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6213),
                            DateUpdated = new DateTime(2025, 8, 7, 11, 53, 21, 908, DateTimeKind.Utc).AddTicks(6213),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award"
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", null)
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Transactions.Payment", "Payment")
                        .WithMany("Vote")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
