// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250808120508_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Award")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pitch")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78b286d7-095c-4e80-a454-f880892215a0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1282),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1285),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f64f0444-c0d4-4df2-a1b4-762959d5f354"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1368),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1369),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("6de60535-1ec3-4621-a39b-bbc12ce71899"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1373),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1373),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("df8103f6-848c-48b2-abde-c4f1215183ed"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1376),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1377),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("c4e18beb-a302-468b-bac7-8d619c1cec81"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1380),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1380),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("01ffda8e-784e-41f7-abfa-ad074515ffe9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1383),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1383),
                            IsDeleted = false,
                            Name = "Most Creative Baker",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9eff98ea-d5e1-4a80-9011-c70abbf3faa4"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1386),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1387),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("27c303db-cd34-4937-acff-54a1aaab9f69"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1389),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1390),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("5dec334b-144c-4372-b474-a8871886094a"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1393),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1393),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a310ad01-cace-4526-9885-e65056283f2d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1400),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1401),
                            IsDeleted = false,
                            Name = "Craft Mastery Award",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("70f140f8-20f6-44dd-b508-9f9deed2cb05"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1404),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1404),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("fbfe531b-65ca-43cf-ad26-b05703fd7298"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1407),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1407),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("12b8e2da-d52b-4152-8a7a-33a06a68adf6"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1410),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1411),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("2c08af38-128f-44c5-bba0-a1c686d3f546"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1413),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1414),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("10864083-5aa8-4139-aebd-306a9b517224"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1417),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1417),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("26c6f3e3-9926-4ea8-beba-95d81fb0bade"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1420),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("6f51e185-e78a-45ab-b419-fc07a20de354"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1423),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1424),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("8a3aefe1-6830-4948-a99d-37bdef65e110"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1430),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("661fb8da-da25-4aa9-b3a6-e9266c50d2a0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1433),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1433),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d9721ba0-52e0-4436-b51b-c144c098287d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1436),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1436),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("50e63d5c-3324-47d1-b6dc-f4e4a6aac065"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1439),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1440),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("10dbfde8-b914-41a1-99d9-e14398c1deb0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1442),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1443),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f539d32b-8e39-40fe-b1f7-5910d45e9308"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1446),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1446),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e9ede2c7-7e24-4dde-a1a8-a6e7d904b2ea"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1449),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1449),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("b9989359-33d2-4e09-b125-296ec312680f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1452),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1452),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("8e49843f-aab0-4bac-bed2-0ec269175953"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1458),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1459),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award",
                            Pitch = false
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnersPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessCategoryId");

                    b.ToTable("BusinessPitch");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.PitchPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PitchPrice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3307b7b-b3f1-439b-8172-69ae23351229"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1735),
                            DateUpdated = new DateTime(2025, 8, 8, 12, 5, 7, 932, DateTimeKind.Utc).AddTicks(1736),
                            IsDeleted = false,
                            Price = 15000m
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "BusinessCategory")
                        .WithMany()
                        .HasForeignKey("BusinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BusinessCategory");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
