// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250808111203_awardandpitchcategory")]
    partial class awardandpitchcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Award")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pitch")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82cb1716-99da-438a-8d2c-38273e68ce8f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6863),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6869),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("656e1364-ce03-4222-9812-7378d357ac1f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6946),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6947),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a3e227b7-1bc3-4a54-8f45-984ad0925d8b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6954),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6955),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9a9fcd29-96c2-4dae-a1cf-f13a9b76a1ce"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6961),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6962),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a08a4187-1db3-4506-9216-183f930bba14"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6967),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6968),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f4241592-c258-4a9a-9852-2e9d52aadc28"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6973),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6974),
                            IsDeleted = false,
                            Name = "Most Creative Baker",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("cb40ec30-6ab4-4809-9915-878877b73434"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6998),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(6998),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e557d476-d8d5-434f-9d46-52a9db984879"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7004),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7004),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("624c7db4-cfbb-48a1-a01a-253a4057a02c"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7010),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7011),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("dc9ce812-052c-4f32-9bb5-db64dd8d80da"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7016),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7017),
                            IsDeleted = false,
                            Name = "Craft Mastery Award",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("96482c93-b1c9-4f65-9978-e222c9f33121"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7047),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7048),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("7b0886f7-b822-461b-8848-01063007d366"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7055),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7055),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("19e03f10-8ea5-440c-89fc-6d5cc989a2ed"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7062),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7062),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e8f0d27b-439a-4fa3-8f95-b89783029472"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7067),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7068),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e2ab5d97-7170-4802-8975-c6bb00b29f04"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7080),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7081),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("6c27d4b1-7d4c-4e44-b81e-ddb8054026a2"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7086),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7087),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("001e206c-e584-47d0-9c7b-3eeee824fd2f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7093),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7094),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f98c63d7-8387-4f2d-a068-def29a70df5d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7099),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7100),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("757e6f2f-058e-4d66-bf08-ddeed65a0d0b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7105),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7106),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("4ad60ec4-406c-4d7e-9a1d-d9a4db0e4096"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7110),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7111),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f4af0081-d875-4bd6-9ace-0daad09f47bf"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7116),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7117),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("99a933f3-3331-4e42-a722-b64fd0d2c75b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7122),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7123),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ea5680cd-6f2b-47b2-9206-f1edb4574149"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7135),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7135),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("eb94aff6-00e0-4318-a627-d9e905103a74"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7140),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7141),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e38bd9ed-8879-4e28-9401-5e7e4a4a2d13"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7146),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7147),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("03679c8f-10ae-4006-a502-8283baf4e0fc"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7151),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7152),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award",
                            Pitch = false
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnersPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessCategoryId");

                    b.ToTable("BusinessPitch");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.PitchPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PitchPrice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f284f91a-601e-4110-a5c6-6b7495503caa"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7700),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 12, 1, 730, DateTimeKind.Utc).AddTicks(7701),
                            IsDeleted = false,
                            Price = 15000m
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Transactions.Payment", "Payment")
                        .WithMany("Vote")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominee");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "BusinessCategory")
                        .WithMany()
                        .HasForeignKey("BusinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BusinessCategory");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
