// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250902125200_exibition")]
    partial class exibition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Award")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pitch")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9e496f9-8aee-4559-90cc-8ff37c2ac5fe"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(253),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(256),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("540a4e83-eefa-435c-90cf-e5926c0ac326"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(296),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(296),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9cda9241-0b26-42c1-8108-2b41dcf21161"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(299),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(299),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("157bab4a-5d7c-415c-87c0-b034b0a24aec"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(313),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(313),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ce64e040-23bd-41de-997a-8bd1c6429bdb"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(315),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(315),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e3293a7f-0ade-4a55-b962-8be0a91e4fa3"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(318),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(318),
                            IsDeleted = false,
                            Name = "Most Creative Baker",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("5703aac3-b8c8-48a9-a9a3-e46e4edc89e9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(320),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(321),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("86c42e48-9390-4bc1-906a-9de6a7fa7041"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(323),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(323),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("981908d6-4fcc-4e04-8846-854bb745ae1e"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(325),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(325),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("45b9b927-2908-498c-8f82-f53d8e872c89"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(327),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(328),
                            IsDeleted = false,
                            Name = "Craft Mastery Award",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("1130787a-ac2d-4e0b-90f8-b270b471f121"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(330),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(330),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("598e3e96-82c7-440d-93f3-817130c2404e"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(336),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(336),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("4423d681-c799-43e7-b9ff-b76729c1e6f4"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(338),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(338),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d2aead3d-af26-4896-9b3e-39fd3d686192"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(340),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(340),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("5df4f5ea-de3c-4147-b7f4-a6c2f91a1c1b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(342),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(343),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("53a69d78-a431-4d25-beb5-ede1b9993caf"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(345),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(345),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ffdbb1b1-58cc-44b1-9e4a-47a401d73c06"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(347),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(347),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f64ae92a-d2b3-4b90-8608-8ffd16ef8b1d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(349),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(349),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ea736d6b-ef8e-4695-a6cd-db4234eeaaf6"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(351),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(351),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("563e007a-bf1c-41d7-8f6c-0fef2c1753e0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(356),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(357),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("8d2db3ac-49e9-4716-86fa-b85f642deae2"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(358),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(359),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("bbbfb182-c51a-4a0e-bb95-7879cde84af6"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(361),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(361),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f59df638-1334-4996-bbcf-86b0037e65b2"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(363),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(363),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("2b0dadd4-88d5-4bab-b397-74697a915a05"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(365),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(366),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("60075000-5d59-4f4e-afce-a3ababac8c2e"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(367),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(368),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("2fc208d7-c600-4dd8-9453-8a4ed0f3f6be"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(370),
                            DateUpdated = new DateTime(2025, 9, 2, 12, 51, 59, 257, DateTimeKind.Utc).AddTicks(370),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award",
                            Pitch = false
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnersPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("BusinessPitch");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.ExibitionStands", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitibionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitibitionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTokHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ExibitionStand");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.PitchPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PitchPrice");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExibitionStandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
