// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250902155048_dinerticket")]
    partial class dinerticket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Award")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pitch")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f59a7a9d-677f-47db-ab11-24881bdeb5e9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2842),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2848),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d906704e-a7fb-4b17-8d81-8f10ddfe1ed7"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2970),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2970),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("cbf1ceea-aff3-4992-8be4-fb4c119b73fe"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2977),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2978),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("57e00e4d-eaa6-452e-9c7d-a5662b38621f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2983),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2984),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("133f1911-9f84-4d27-b77d-bcb5c7bd7cd9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2987),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2988),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("b1bf7036-c277-4e22-9000-19b571e80cda"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2993),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2993),
                            IsDeleted = false,
                            Name = "Most Creative Baker",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e1155b2c-7125-42a5-90d3-3bb321d788af"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(2999),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3000),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("5faf92c6-5437-4242-90e9-cebc83ffada6"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3005),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3005),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9cd50e90-c54e-41b6-bdde-1ee072d589c9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3010),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3011),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("875aca65-ecc6-46f8-bd00-a90e6c1ac035"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3025),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3025),
                            IsDeleted = false,
                            Name = "Craft Mastery Award",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("c0a66cec-3d73-43d0-af44-20c0e9b8d67e"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3029),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3030),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("00edfb3d-e7de-4c63-83bd-39218de22bb6"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3034),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3034),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("c08c7672-1968-4ccc-a198-4020db94fdf0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3039),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3040),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("4386cc6a-03c8-48b8-8286-239e6131ded2"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3044),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3045),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("2d713b6c-ee2a-45a3-8832-3db157cebc83"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3049),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3050),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("8390e87f-2d7b-49b5-9071-f4385d21b51d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3054),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3054),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("f18d9f37-7cf3-48e2-90a4-1294ea53b50d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3059),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3059),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ad405f2a-9868-4feb-894c-aef942da9693"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3069),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3070),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("529cd1dc-c66c-4e99-92ba-58530e787b3d"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3076),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3077),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("aa71ad01-314a-4f7e-9ab7-bc1239aab10a"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3080),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3081),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("0760a065-69ad-434c-97c2-4a479a2aaae9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3085),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3086),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9a069e76-4f82-49fc-a369-4f66cc69d3ad"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3090),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3091),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a3f8d09a-cba2-4689-b2bc-b7fa38bd65ff"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3095),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3096),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("5b3a07bd-9549-4137-a56e-7bbb207e8c3f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3100),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3101),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("847e4009-4eff-434f-9312-2383d2aa3988"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3105),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3106),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("7f9e8e49-518c-4359-ae1b-6e70fec36b99"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3117),
                            DateUpdated = new DateTime(2025, 9, 2, 15, 50, 47, 538, DateTimeKind.Utc).AddTicks(3118),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award",
                            Pitch = false
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnersPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("BusinessPitch");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.DinnerTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DinnerTickets");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.ExibitionStands", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitibionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitibitionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTokHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ExibitionStand");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.PitchPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PitchPrice");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExibitionStandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
