// <auto-generated />
using System;
using IMSBackend.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMSBackend.Persistence.Migrations
{
    [DbContext(typeof(IMSBackendContext))]
    [Migration("20250808114803_adjustment")]
    partial class adjustment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.ForgotPasswordOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedExpiryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Award")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pitch")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("454a53b4-c8b7-47cb-9c53-0e05d5d70354"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5550),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5554),
                            IsDeleted = false,
                            Name = "African Women’s Fashion Talent of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d7113b36-1e3c-455e-a0a0-c6e845779737"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5646),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5647),
                            IsDeleted = false,
                            Name = "Outstanding Fashion Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("bb9d93a8-2488-4f97-9c5e-11d3685c0563"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5650),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5651),
                            IsDeleted = false,
                            Name = "Beauty and Personal Care Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e2648237-0705-45b8-9637-3aeb084df613"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5654),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5654),
                            IsDeleted = false,
                            Name = "Outstanding Beverage Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("011256a4-1c2b-46fe-bdf3-e0ac1346fa83"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5657),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5657),
                            IsDeleted = false,
                            Name = "Top Rated, Dessert and Finger Food",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("697d012f-0328-418b-a60d-21c805068590"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5660),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5660),
                            IsDeleted = false,
                            Name = "Most Creative Baker",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d0447c95-7683-495d-81a4-5e8ab551b92f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5664),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5664),
                            IsDeleted = false,
                            Name = "Most Innovative Product of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a6dfdac3-caa6-43c6-8f2e-80a9a13df1f8"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5667),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5668),
                            IsDeleted = false,
                            Name = "Best Indigenous Snack brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ca9c4a55-ee67-4a78-a652-83f016270e63"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5670),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5671),
                            IsDeleted = false,
                            Name = "Outstanding Quality Hair Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("08fe0f4c-7d79-4d95-a6bd-2c4c083bba34"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5678),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5678),
                            IsDeleted = false,
                            Name = "Craft Mastery Award",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("bfc23686-e4f9-4ec7-a994-de6af5e9f1f9"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5681),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5681),
                            IsDeleted = false,
                            Name = "Best Emerging Food brand of the year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("d988d8fe-b2f0-4cd9-b6ec-a0ed605d2321"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5696),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5696),
                            IsDeleted = false,
                            Name = "Creative Bridal Hairstylist of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a9983ad5-5704-431d-ab29-570cf4689cb2"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5699),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5699),
                            IsDeleted = false,
                            Name = "Top Rated, Event Catering Brand",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("1095ee84-2638-49e7-b71b-2e1860ab83ee"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5702),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5702),
                            IsDeleted = false,
                            Name = "Fastest Growing Perfume Business",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("dd7a3e06-18f3-4578-a085-045737af959a"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5705),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5705),
                            IsDeleted = false,
                            Name = "Outstanding Female Fashion Designer of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("4528a8ce-2631-4411-9b60-17b4d6d325b5"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5708),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5708),
                            IsDeleted = false,
                            Name = "Outstanding Fenalr Entrepreneur in Agro-Retail",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("7823e5ed-617f-41ec-9a34-62c2b87b1d7e"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5711),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5711),
                            IsDeleted = false,
                            Name = "Textile Manufacturing Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("ae15dd5b-74dc-41ad-987e-3eb1618cdb90"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5717),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5717),
                            IsDeleted = false,
                            Name = "Outstanding Female Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("457887b7-f55f-4d81-8e29-da0240e4f97b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5721),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5721),
                            IsDeleted = false,
                            Name = "Fabric Vendor of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("e8bb2082-41ed-4617-84e1-47642d1d55f0"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5724),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5725),
                            IsDeleted = false,
                            Name = "Best Emerging Entrepreneur of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a38ffc23-5941-4e69-908b-097349fbc32f"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5727),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5727),
                            IsDeleted = false,
                            Name = "Best Emerging Fashion Retail Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("9749500e-23e5-4a63-b971-e1ff37598129"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5730),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5730),
                            IsDeleted = false,
                            Name = "Outstanding Full-Service Beauty SPA",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("1ea5465e-29e8-4d45-9c9c-6dc1ab3a2e40"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5733),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5733),
                            IsDeleted = false,
                            Name = "Media and Entertainment Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("a91628b2-53ce-4f50-86c4-1f0e0cb19a48"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5736),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5736),
                            IsDeleted = false,
                            Name = "Creative Branding and Printing Excellence",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("47d1fb8c-6594-4afd-b4b7-e0f32e25e93b"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5738),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5739),
                            IsDeleted = false,
                            Name = "Health and Wellness Brand of the Year",
                            Pitch = false
                        },
                        new
                        {
                            Id = new Guid("41837871-21fb-4588-8f0b-6223655dd694"),
                            Award = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5745),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(5745),
                            IsDeleted = false,
                            Name = "Brand Evolution Excellence Award",
                            Pitch = false
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nominees");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<Guid>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnersPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessCategoryId");

                    b.ToTable("BusinessPitch");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.PitchPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PitchPrice");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a2c6c47-fa12-4c9f-9c7a-d649bfdb63b9"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(6157),
                            DateUpdated = new DateTime(2025, 8, 8, 11, 48, 2, 990, DateTimeKind.Utc).AddTicks(6158),
                            IsDeleted = false,
                            Price = 15000m
                        });
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountExpected")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Account.RegistrationOtp", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Vote", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Award.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Transactions.Payment", null)
                        .WithMany("Vote")
                        .HasForeignKey("PaymentId");

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.BusinessPitches.BusinessPitch", b =>
                {
                    b.HasOne("IMSBackend.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMSBackend.Domain.Entities.Award.Category", "BusinessCategory")
                        .WithMany()
                        .HasForeignKey("BusinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BusinessCategory");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Award.Nominee", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("IMSBackend.Domain.Entities.Transactions.Payment", b =>
                {
                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
