using IMSBackend.Application.Contracts;
using IMSBackend.Common;
using IMSBackend.Domain.Entities.CustomerDomain;
using IMSBackend.Domain.Entities.EventDomain;
using IMSBackend.Domain.Shared;
using IMSBackend.Infrastructure.Settings;
using IMSBackend.Persistence.Migrations;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IMSBackend.Application.Features.CheckoutFeatures
{
    public class ProcessEventOrderCommandHandler : IRequestHandler<ProcessEventOrderCommand, Result<string>>
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPaymentService _paymentService;
        private readonly ILogger<ProcessEventOrderCommand> _logger;
        private readonly CheckoutSettings _settings;

        public ProcessEventOrderCommandHandler(IUnitOfWork unitOfWork, IPaymentService paymentService, ILogger<ProcessEventOrderCommand> logger, IOptions<CheckoutSettings> settings)
        {
            _unitOfWork = unitOfWork;
            _paymentService = paymentService;
            _logger = logger;
            _settings = settings.Value;
        }
        public async Task<Result<string>> Handle(ProcessEventOrderCommand request, CancellationToken cancellationToken)
        {
            // 1. Get the Execution Strategy. This handles retries and transaction management.
            var strategy = _unitOfWork.GetExecutionStrategy();

            try
            {
                // 2. Wrap the entire atomic operation inside ExecuteAsync for retry logic.
                // We manually manage the transaction and isolation level inside the delegate 
                // to bypass compilation issues with ExecuteInTransactionAsync overloads.
                return await strategy.ExecuteAsync<Result<string>>(
                    // FIX: The delegate must accept a CancellationToken (named 'token' here)
                    async (token) =>
                    {
                        // Start the transaction manually with Serializable isolation level.
                        // This is retried by the strategy if transient errors occur here.
                        await using var transaction = await _unitOfWork.BeginTransactionAsync(IsolationLevel.Serializable, token);

                        try
                        {
                            // This Guid would typically be generated by an Order service or during the overall order flow
                            Guid orderId = Guid.NewGuid();

                            decimal subtotal = 0;
                            decimal taxableSubtotal = 0;

                            // Map to store ticket details and vendor tax setting
                            var ticketMap = new Dictionary<Guid, (decimal Price, Guid VendorId, string CategoryName, string EventTitle, string VenueName, DateTime EventDate, DateTime EventTime, int Capacity, TicketCategory Entity)>();
                            var vendorTaxSettings = new Dictionary<Guid, bool>();
                            var vendorIdsInOrder = new HashSet<Guid>();

                            // 1. Initial Seat Check and Expected Total Calculation (Queries run within the transaction)
                            foreach (var itemDto in request.TicketBookingDto)
                            {
                                // Retrieve the ticket category entity with its parent Event and Vendor
                                // The query is inside the transaction boundary.
                                var ticketCategory = await _unitOfWork.TicketCategoryRepository.GetQueryable()
                                    .Include(t => t.Event)
                                    .ThenInclude(e => e.Vendor)
                                    .FirstOrDefaultAsync(t => t.Id == itemDto.TicketCategoryId, token); // Use token

                                // Check 1: Existence and Seat Availability
                                if (ticketCategory == null || ticketCategory.Capacity < itemDto.Quantity)
                                {
                                    // IMPORTANT: Since we return Failure here, we MUST roll back the transaction.
                                    await transaction.RollbackAsync(token); // Use token

                                    string message = ticketCategory == null
                                        ? "Ticket category not found."
                                        : $"Seats insufficient for {ticketCategory.Name}. Available: {ticketCategory.Capacity}, Requested: {itemDto.Quantity}.";
                                    _logger.LogInformation(message);
                                    return await Result<string>.FailureAsync(message);
                                }

                                var vendor = ticketCategory.Event.Vendor;
                                Guid vendorId = vendor.Id;

                                // Get or cache the vendor's tax preference
                                if (!vendorTaxSettings.ContainsKey(vendorId))
                                {
                                    vendorTaxSettings[vendorId] = vendor.PassTaxToCustomer;
                                }

                                // Calculate item subtotal
                                decimal itemSubtotal = ticketCategory.Price * itemDto.Quantity;
                                subtotal += itemSubtotal;

                                // Apply item subtotal to taxable total ONLY IF vendor passes tax on
                                if (vendorTaxSettings[vendorId])
                                {
                                    taxableSubtotal += itemSubtotal;
                                }

                                // Store entity reference and details for later use
                                ticketMap[ticketCategory.Id] = (
                                    ticketCategory.Price,
                                    vendorId,
                                    ticketCategory.Name,
                                    ticketCategory.Event.Title,
                                    ticketCategory.Event.VenueName,
                                    ticketCategory.Event.EventDate,
                                    ticketCategory.Event.EventTime,
                                    ticketCategory.Capacity,
                                    ticketCategory
                                );

                                vendorIdsInOrder.Add(vendorId);
                            }

                            // 2. Finalize Expected Amount Calculation
                            decimal taxAmount = taxableSubtotal * _settings.TaxRate;
                            decimal feeAmount = subtotal * _settings.PaymentGatewayCharges;
                            decimal finalTotalExpected = subtotal + taxAmount + feeAmount;

                            // 3. PAYMENT VERIFICATION (CRITICAL STEP)
                            // This external call is outside the database transaction but inside the retry block.
                            var paymentResult = await _paymentService.GetTransactionStatus(request.ReferenceNumber);

                            if (paymentResult?.data == null || paymentResult.status?.ToLower() != "success")
                            {
                                await transaction.RollbackAsync(token); // Use token
                                _logger.LogInformation($"Payment verification failed or transaction was not successful for this {request.ReferenceNumber} reference");
                                return await Result<string>.FailureAsync($"Payment verification failed or transaction was not successful for this {request.ReferenceNumber} reference");
                            }

                            // Verify that the amount paid matches the expected final total
                            bool amountMatches = (Math.Round(finalTotalExpected, 2) == Math.Round(paymentResult.data.amount, 2) || Math.Round(paymentResult.data.amount, 2) > Math.Round(finalTotalExpected, 2));

                            if (!amountMatches)
                            {
                                await transaction.RollbackAsync(token); // Use token
                                                                        // Log detailed mismatch for security/fraud audit
                                string message = $"Payment verification failed: Expected amount {finalTotalExpected:N2} does not match actual amount {paymentResult.data.amount:N2}. A potential fraud attempt has been flagged.";
                                _logger.LogInformation(message);
                                return await Result<string>.FailureAsync(message);
                            }

                            // 4. Seat Deduction and Ticket Booking
                            var purchaseDate = DateTime.UtcNow;

                            foreach (var itemDto in request.TicketBookingDto)
                            {
                                var ticketData = ticketMap[itemDto.TicketCategoryId];
                                var ticketToDeduct = ticketData.Entity;

                                // Deduct seats in memory
                                ticketToDeduct.Capacity -= itemDto.Quantity;
                                await _unitOfWork.TicketCategoryRepository.Update(ticketToDeduct);

                                // Create the booked ticket record
                                var bookedTicket = new BookedTicket
                                {
                                    OrderId = orderId,
                                    CustomerId = request.CustomerId,
                                    VendorId = ticketData.VendorId,
                                    CustomerEmail = request.CustomerEmail,
                                    TicketCategoryId = itemDto.TicketCategoryId,
                                    Quantity = itemDto.Quantity,
                                    UnitPrice = ticketData.Price,
                                    PurchaseDate = purchaseDate,
                                    CustomerName = request.CustomerName,
                                    EventTitle = ticketData.EventTitle,
                                    TicketCategoryName = ticketData.CategoryName,
                                    VenueName = ticketData.VenueName,
                                    EventDate = ticketData.EventDate.Date,
                                    EventTime = ticketData.EventTime,
                                    TicketNumber = $"{ticketData.EventTitle.Substring(0, 2).ToUpper()}-{ticketData.CategoryName.Substring(0, 2).ToUpper()}-{Guid.NewGuid().ToString().Substring(0, 8)}"
                                };

                                await _unitOfWork.BookedEventRepository.AddAsync(bookedTicket);
                            }

                            // FIX 2: Handle VendorCustomer creation robustly to prevent duplicate key and FK conflicts.
                            foreach (var vendorId in vendorIdsInOrder)
                            {
                                // Check if the VendorCustomer record already exists to prevent duplicate insertion
                                var existingVc = await _unitOfWork.VendorCustomerRepository.GetQueryable()
                                    .FirstOrDefaultAsync(vc => vc.VendorId == vendorId && vc.CustomerId == request.CustomerId, token);

                                if (existingVc == null)
                                {
                                    // If it doesn't exist, add it.
                                    await _unitOfWork.VendorCustomerRepository.AddAsync(new VendorCustomer
                                    {
                                        VendorId = vendorId,
                                        CustomerId = request.CustomerId, // Use the retrieved Customer ID (Crucial Fix for FK)
                                        LastPurchaseDate = purchaseDate
                                    });
                                }
                                else
                                {
                                    // If it exists, update the last purchase date.
                                    existingVc.LastPurchaseDate = purchaseDate;
                                    // No explicit Update call needed if UnitOfWork tracks entities automatically
                                }
                            }

                            // 5. Final Save
                            // The Save operation is now bound to the manually started transaction.
                            await _unitOfWork.Save(token); // Use token

                            // COMMIT TRANSACTION
                            await transaction.CommitAsync(token); // Use token

                            _logger.LogInformation($"Tickets booked successfully! Payment verified. Your tickets are ready for download. {orderId}");
                            return await Result<string>.SuccessAsync($"Tickets booked successfully! Payment verified. Your tickets are ready for download.{orderId}");
                        }
                        catch (Exception)
                        {
                            // Rollback on any internal failure before the exception propagates, 
                            // ensuring the using statement's Dispose doesn't throw if the transaction is still pending.
                            await transaction.RollbackAsync(token); // Use token
                            throw; // Re-throw the exception for the Execution Strategy to handle (retry or bubble up).
                        }
                    },
                    cancellationToken // Passing the mandatory cancellation token for ExecuteAsync
                );
            }
            catch (Exception ex)
            {
                // Catch any exception that escapes the retry block (e.g., persistent errors or exceeded retry count).
                // The transaction is already rolled back by the internal catch block.
                _logger.LogError(ex, "A critical error occurred during transaction execution. The transaction was automatically rolled back by the execution strategy.");
                return await Result<string>.FailureAsync("An unexpected error occurred during ticket booking.");
            }
        }
    }
}
