using IMSBackend.Application.Contracts;
using IMSBackend.Common;
using IMSBackend.Domain.Entities.CustomerDomain;
using IMSBackend.Domain.Entities.EventDomain;
using IMSBackend.Domain.Shared;
using IMSBackend.Infrastructure.Settings;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IMSBackend.Application.Features.CheckoutFeatures
{
    public class ProcessEventOrderCommandHandler : IRequestHandler<ProcessEventOrderCommand, Result<string>>
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPaymentService _paymentService;
        private readonly ILogger<ProcessEventOrderCommand> _logger;
        private readonly CheckoutSettings _settings;

        public ProcessEventOrderCommandHandler(IUnitOfWork unitOfWork, IPaymentService paymentService, ILogger<ProcessEventOrderCommand> logger, IOptions<CheckoutSettings> settings)
        {
            _unitOfWork = unitOfWork;
            _paymentService = paymentService;
            _logger = logger;
            _settings = settings.Value;
        }
        public async Task<Result<string>> Handle(ProcessEventOrderCommand request, CancellationToken cancellationToken)
        {
            // Use Serializable isolation level to prevent double-booking issues (race conditions)
            using var transaction = await _unitOfWork.BeginTransactionAsync(IsolationLevel.Serializable, cancellationToken);

            // This Guid would typically be generated by an Order service or during the overall order flow
            Guid orderId = Guid.NewGuid();

            try
            {
                decimal subtotal = 0;
                decimal taxableSubtotal = 0;

                // Map to store ticket details and vendor tax setting
                var ticketMap = new Dictionary<Guid, (decimal Price, Guid VendorId, string CategoryName, string EventTitle, string VenueName, DateTime EventDate, DateTime EventTime, int Capacity, TicketCategory Entity)>();
                var vendorTaxSettings = new Dictionary<Guid, bool>();
                var vendorIdsInOrder = new HashSet<Guid>();

                // 1. Initial Seat Check and Expected Total Calculation
                foreach (var itemDto in request.TicketBookingDto)
                {
                    // Retrieve the ticket category entity with its parent Event and Vendor
                    var ticketCategory = await _unitOfWork.TicketCategoryRepository.GetQueryable()
                        .Include(t => t.Event)
                        .ThenInclude(e => e.Vendor)
                        .FirstOrDefaultAsync(t => t.Id == itemDto.TicketCategoryId, cancellationToken);

                    // Check 1: Existence and Seat Availability
                    if (ticketCategory == null || ticketCategory.Capacity < itemDto.Quantity)
                    {
                        // Rollback immediately if a stock check fails
                        await transaction.RollbackAsync(cancellationToken);
                        string message = ticketCategory == null
                            ? "Ticket category not found."
                            : $"Seats insufficient for {ticketCategory.Name}. Available: {ticketCategory.Capacity}, Requested: {itemDto.Quantity}.";
                        _logger.LogInformation(message);
                        return await Result<string>.FailureAsync(message);
                    }

                    var vendor = ticketCategory.Event.Vendor;
                    Guid vendorId = vendor.Id;

                    // Get or cache the vendor's tax preference
                    if (!vendorTaxSettings.ContainsKey(vendorId))
                    {
                        vendorTaxSettings[vendorId] = vendor.PassTaxToCustomer;
                    }

                    // Calculate item subtotal
                    decimal itemSubtotal = ticketCategory.Price * itemDto.Quantity;
                    subtotal += itemSubtotal;

                    // Apply item subtotal to taxable total ONLY IF vendor passes tax on
                    if (vendorTaxSettings[vendorId])
                    {
                        taxableSubtotal += itemSubtotal;
                    }

                    // Store entity reference and details for later use
                    ticketMap[ticketCategory.Id] = (
                        ticketCategory.Price,
                        vendorId,
                        ticketCategory.Name, // Category Name
                        ticketCategory.Event.Title, // Event Title
                        ticketCategory.Event.VenueName, // Venue Name
                        ticketCategory.Event.EventDate, // Event Date
                        ticketCategory.Event.EventTime, // Event Time
                        ticketCategory.Capacity,
                        ticketCategory
                    );

                    vendorIdsInOrder.Add(vendorId);
                }

                // 2. Finalize Expected Amount Calculation
                decimal taxAmount = taxableSubtotal * _settings.TaxRate;
                decimal feeAmount = subtotal * _settings.PaymentGatewayCharges;
                decimal finalTotalExpected = subtotal + taxAmount + feeAmount;

                // 3. PAYMENT VERIFICATION (CRITICAL STEP)
                var paymentResult = await _paymentService.GetTransactionStatus(request.ReferenceNumber);

                if (paymentResult?.data == null || paymentResult.status?.ToLower() != "success")
                {
                    await transaction.RollbackAsync(cancellationToken);
                    _logger.LogInformation($"Payment verification failed or transaction was not successful for this {request.ReferenceNumber} reference");
                    return await Result<string>.FailureAsync($"Payment verification failed or transaction was not successful for this {request.ReferenceNumber} reference");
                }

                // Verify that the amount paid matches the expected final total
                bool amountMatches = (Math.Round(finalTotalExpected, 2) == Math.Round(paymentResult.data.amount, 2) || Math.Round(finalTotalExpected, 2) > Math.Round(paymentResult.data.amount, 2));

                if (!amountMatches)
                {
                    await transaction.RollbackAsync(cancellationToken);
                    // Log detailed mismatch for security/fraud audit
                    _logger.LogInformation($"Payment verification failed: Expected amount {finalTotalExpected:N2} does not match actual amount {paymentResult.data.amount:N2}. A potential fraud attempt has been flagged.");
                    return await Result<string>.FailureAsync($"Payment verification failed: Expected amount {finalTotalExpected:N2} does not match actual amount {paymentResult.data.amount:N2}. A potential fraud attempt has been flagged.");
                }
                // Payment is verified and amount is correct. Proceed with state changes.

                // 4. Seat Deduction and Ticket Booking
                var purchaseDate = DateTime.UtcNow;

                foreach (var itemDto in request.TicketBookingDto)
                {
                    var ticketData = ticketMap[itemDto.TicketCategoryId];
                    var ticketToDeduct = ticketData.Entity;

                    // Deduct seats in memory (assuming Capacity tracks available seats)
                    ticketToDeduct.Capacity -= itemDto.Quantity;
                    await _unitOfWork.TicketCategoryRepository.Update(ticketToDeduct);


                    // Create the booked ticket record (similar to OrderItem)
                    var bookedTicket = new BookedTicket
                    {
                        OrderId = orderId,
                        CustomerId = request.CustomerId,
                        VendorId = ticketData.VendorId,
                        TicketCategoryId = itemDto.TicketCategoryId,
                        Quantity = itemDto.Quantity,
                        UnitPrice = ticketData.Price,
                        PurchaseDate = purchaseDate,

                        // Populate new ticket design fields
                        CustomerName = request.CustomerName,
                        CustomerEmail = request.CustomerEmail,
                        EventTitle = ticketData.EventTitle,
                        TicketCategoryName = ticketData.CategoryName,
                        VenueName = ticketData.VenueName,
                        EventDate = ticketData.EventDate.Date, // Store date only
                        EventTime = ticketData.EventTime, // Store time only
                        TicketNumber = $"{ticketData.EventTitle.Substring(0, 2).ToUpper()}-{ticketData.CategoryName.Substring(0, 2).ToUpper()}-{Guid.NewGuid().ToString().Substring(0, 8)}" // Simple unique identifier
                    };

                   await _unitOfWork.BookedEventRepository.AddAsync(bookedTicket);
                }

                // 5. Update Vendor-Customer CRM Relationship
                var customerId = request.CustomerId;
                var now = DateTime.UtcNow;

                foreach (var vendorId in vendorIdsInOrder)
                {
                    var existingRelationship = _unitOfWork.VendorCustomerRepository.GetQueryable()
                        .FirstOrDefault(vc => vc.VendorId == vendorId && vc.CustomerId == customerId);

                    if (existingRelationship == null)
                    {
                       await _unitOfWork.VendorCustomerRepository.AddAsync(new VendorCustomer
                        {
                            VendorId = vendorId,
                            CustomerId = customerId,
                            LastPurchaseDate = now
                        });
                    }
                    else
                    {
                        existingRelationship.LastPurchaseDate = now;
                        await _unitOfWork.VendorCustomerRepository.Update(existingRelationship);
                    }
                }

                // 6. Final Save and Commit
                await _unitOfWork.Save(cancellationToken);
                await transaction.CommitAsync(cancellationToken);

                _logger.LogInformation($"Tickets booked successfully! Payment verified. Your tickets are ready for download. {orderId}");
                return await Result<string>.SuccessAsync($"Tickets booked successfully! Payment verified. Your tickets are ready for download.{orderId}");
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync(cancellationToken);
                // Log the exception for debugging purposes
                return await Result<string>.FailureAsync("An unexpected error occurred during ticket booking.");
            }
        }
    }
}
